### ISSUE TITLE
Request fakes

### ISSUE THREAD

**Issue by backus** [BlockScore/blockscore-ruby#37]
I'm creating this issue so @DelmerGA, @sirwolfgang, and I can discuss options for faking out API requests for the test suite.  In separate comments I will

1. explain what we have in place right now and why it is the way it is
2.  briefly introduce the sinatra fake and VCR options we discussed in our standup

I'd like both of your input for weighing the options here.  I'll also write up what I think would be a nice solution but I'll hold off on posting it until some discussion has begun so I don't bias

**Comment by backus** [comment]
### Current request faking

Right now we catch all requests with webmock

```ruby
# spec_helper.rb
config.before(:each) do
    @api_stub = stub_request(:any, Spec::STUB_PATTERN)
      .with(headers: Spec::HEADERS)
      .to_return(&Spec.method(:webmock_handler))
end

# spec.rb
module Spec
# ...

  # Handle a webmock request
  #
  # @param request
  # @return [undefined]
  #
  # @api public
  def webmock_handler(request)
    request = BlockScore::StubbedRequest.new(request)
    BlockScore::StubbedResponse::Router.call(request).response
  end
end
```

Then these requests are handled with `StubbedRequest` and `StubbedResponse`.  Basically, these files define some basic behavior for how to route different requests.  It all just boils down to a bunch of conditionals:

```ruby
route(Error)    { |stub| StubbedResponse::Error::MAP.key?(stub.id)               }
route(Retrieve) { |stub| BlockScore::StubbedResponse::Error::MAP.key?(stub.id)   }
route(Create)   { |stub| stub.http_method.equal?(:post) && !stub.has?(:action)   }
route(Retrieve) { |stub| stub.http_method.equal?(:delete) && !stub.has?(:action) }
route(List)     { |stub| !stub.has?(:id) && stub.http_method.equal?(:get)        }
route(List)     { |stub| stub.action.eql?('hits')                                }
route(History)  { |stub| stub.action.eql?('history')                             }
route(Retrieve) { |stub| stub.action.eql?('score')                               }
route(Retrieve) { |stub| stub.http_method.equal?(:patch)                         }
route(Retrieve) { |stub| stub.has?(:id) && stub.http_method.equal?(:get)         }
```

This system is pretty lacking right now.  This is just my quick refactor of the [spaghetti request stubbing we had before](https://github.com/BlockScore/blockscore-ruby/blob/2d7a7a98b78ced2ee23bac02e80301359dd4c50f/test/support/response.rb).  I'm fine with getting rid of it just because it seems pretty awkward still and unclear at first how to add new request handling

**Comment by backus** [comment]
### Sinatra and VCR

This blog post will likely do a better job than I will do at explaining these options so just read: ["How to Stub External Services in Tests"](https://robots.thoughtbot.com/how-to-stub-external-services-in-tests)

**Comment by DelmerGA** [comment]
I saw this one too: https://robots.thoughtbot.com/faking-apis-in-development-and-staging

**Comment by sirwolfgang** [comment]
My primary concern is cost of change; I'd rather not write/rewrite anything that doesn't have to be. VCR is great at match, and replaying the responses. By having VCR create cassettes based on each test, it normally works fine for state full type of transactions.

Can someone dig up a case, where VCR would not work? Or should we use VCR and handle edge cases that arise, as edge cases, and solve them with Sinatra or whatever when needed?

**Comment by backus** [comment]
Talking with Zane about this more makes me think that the best solution here is just to use VCR as much as possible.  I think VCR has an even bigger leg up here just since we don't risk accidentally introducing subtle differences using VCR like we might if we create a thorough local API fake.  

As I mentioned to @sirwolfgang, I would prefer a solution that makes sure our tests aren't filled with implicit VCR requirements. Either something like making the VCR request matching dynamic (matching `/people/:id` instead of `/people/123`) or by having specific factory traits which just apply specific ids without cluttering the tests much.

I'm going to close the issue. Feel free to reopen and keep discussing here.  I'll be happy with whatever you guys decide on and feel free to just do it without running it by me.
