### ISSUE TITLE
BlockScore::Base should offer an update

### ISSUE THREAD

**Issue by OfTheDelmer** [BlockScore/blockscore-ruby#40]
`BlockScore::Base#update` could have example usage like follows:

``` ruby
person = Person.retrieve("some_id")
person.update(document_type: "ssn", document_value: "0001")
```

**Comment by backus** [comment]
It should probably be part of `BlockScore::Actions::Update`

**Comment by connorjacobsen** [comment]
Should it be `update_attributes`, or something of the like, in order to be more inline with #46?

**Comment by DelmerGA** [comment]
`update` should be fine since `update_attributes` is just an alias for `update`.

**Comment by connorjacobsen** [comment]
Touche. So per @backus' suggestion, just a new method in the `BlockScore::Actions::Update` module?

**Comment by DelmerGA** [comment]
sounds good to me

**Comment by connorjacobsen** [comment]
I am working on this now. I am considering implementing an `:initialize_from` method like Stripe does [here](https://github.com/stripe/stripe-ruby/blob/cdb859911971bef942b3d0993d2ca0626cc0a993/lib/stripe/stripe_object.rb#L314) rather than simply calling `:refresh`. Thoughts?
