### ISSUE TITLE
BlockScore::Base should have better explicit spec coverage

### ISSUE THREAD

**Issue by DelmerGA** [BlockScore/blockscore-ruby#41]
Currently BlockScore::Base is implicitly tested via various specs for particular resources, but it should also have it's own `base_spec.rb` for it's behavior.

**Comment by sirwolfgang** [comment]
Following the "test what you see" concept, Base and Collection are now tested through there use in the lib. PR #43 increases the coverage to 97% on base, and 96% on Collection.
