### ISSUE TITLE
#save is post(ing) NOT patch(ing)

### ISSUE THREAD

**Issue by tjchambers** [BlockScore/blockscore-ruby#64]
tl;dr #save is doing a POST transaction NOT the PATCH transaction, and therefore is creating new content instead of saving existing updates. 

This is generally not what most people think of when saving an existing object:

```
.2.4 :028 > c = BlockScore::Candidate.all.first
 => #<BlockScore::Candidate:0x007f9a4d354758 JSON:{
  "object": "candidate",
  "id": "56b913fc3565650003000d1a",
  "created_at": 1454969852,
  "updated_at": 1454969853,
  "livemode": false,
  "note": null,
  "ssn": "0000",
  "passport": null,
  "date_of_birth": "1992-03-05",
  "name_first": "Joany",
  "name_middle": null,
  "name_last": "Dooley",
  "address_street1": "6251 Consuelo Drive",
  "address_street2": null,
  "address_city": "New Keely",
  "address_subdivision": null,
  "address_postal_code": null,
  "address_country_code": "MR",
  "deleted": true
}>
2.2.4 :029 > c.name_middle = 'Jay'
 => "Jay"
2.2.4 :030 > c
 => #<BlockScore::Candidate:0x007f9a4d354758 JSON:{
  "object": "candidate",
  "id": "56b913fc3565650003000d1a",
  "created_at": 1454969852,
  "updated_at": 1454969853,
  "livemode": false,
  "note": null,
  "ssn": "0000",
  "passport": null,
  "date_of_birth": "1992-03-05",
  "name_first": "Joany",
  "name_middle": "Jay",
  "name_last": "Dooley",
  "address_street1": "6251 Consuelo Drive",
  "address_street2": null,
  "address_city": "New Keely",
  "address_subdivision": null,
  "address_postal_code": null,
  "address_country_code": "MR",
  "deleted": true
}>
2.2.4 :031 > c.save
 => true
2.2.4 :032 > c
 => #<BlockScore::Candidate:0x007f9a4d354758 JSON:{
  "object": "candidate",
  "id": "56ba2d2963616100030006e6", #<-- note: new ID
  "created_at": 1455041833,
  "updated_at": 1455041833,
  "livemode": false,
  "note": null,
  "ssn": "0000",
  "passport": null,
  "date_of_birth": "1992-03-05",
  "name_first": "Joany",
  "name_middle": "Jay",
  "name_last": "Dooley",
  "address_street1": "6251 Consuelo Drive",
  "address_street2": null,
  "address_city": "New Keely",
  "address_subdivision": null,
  "address_postal_code": null,
  "address_country_code": "MR"
}>
```

**Comment by tjchambers** [comment]
The effect of this is multifold:

- The object being saved is not altered, so the changed data is NOT associated with the object ID changed
- If save occurs for a NEW object everything appears fine. A subsequence change of the same Ruby Object will create a duplicate (assuming nothing altered in the interim)
- If the object being saved is for example a `Person` with existing `Question Sets`, then the original stored object still has those questions sets and scores and the new object created has no question sets (it is new)
- When invoked through the Member class, this causes duplicate question set entries to be generated is the member object is saved multiple times (`Member.new(person, question_set)`)
- If the client/customer is saving the referenced objects API Id in their own system for later reference (like sotring person.id after creation), and then they retrieve alter and save that via the API, the saved content is effectively lost to them, unless they retrieve the new ID (see quetion set info above for side effect).

**Comment by tjchambers** [comment]
My current plan is to fix this by...

- Borrowing from the #update logic to do a patch
- Only patch changed attributes that are updateable (stolen from same logic)
- which requires (to be proper) a before and after view of the objects attributes (captured at retrieval - hash diff -> patch)

One concern is that setters and getters MUST update the attributes (I suspect this is already in place, but must be confirmed). If the attributes are readonly after retrieval this would make it interesting. 

Am (VERY?) open to other suggestions.

**Comment by tjchambers** [comment]
As an aside I have reviewed the PHP and Python implementations which do not appear at present to be vulnerable to the same behavior. Python was actually manually tested, and PHP uses a *unsaved attribute array* to maintain the list of dirty attributes.

**Comment by tjchambers** [comment]
It appears this problem IS in fact a bug, but should be relatively easy to remedy on the assumption that Person and Company are not immutable by definition. They are not technically immutable, but there may be some reason (@backus?) that they should be considered immutable for audit trail purposes.

**Comment by alainmeier** [comment]
Yes, they should be considered immutable for audit trail purposes

**Comment by tjchambers** [comment]
@alainmeier  In that case then since they are not presently immutable, I will *fix* the #save issue removing the capability to alter them.

**Comment by alainmeier** [comment]
Sounds good :)

**Comment by tjchambers** [comment]
@alainmeier does it make any business sense for Question Sets to be alterable (aka #save able)?

**Comment by alainmeier** [comment]
Nope, doesn't make sense!

**Comment by tjchambers** [comment]
So from a business viewpoint .save *should* only be visible when editing candidates (matches the API docs). For all other objects the #save method should not be accessible publicly.

**Comment by alainmeier** [comment]
Wait hold on - I completely forgot about the pattern of:

```ruby
c = Company.new(company_params)
c.save
```

Are you including this pattern in your understanding of #save?

**Comment by tjchambers** [comment]
@alainmeier  In truth that should be a one time event. However if you save an already #saved Company today you get ANOTHER Company created. Which is why `save` is not a truly good name for that. **In the API docs there is no option to do what you described, however it does work.
**
My question is what *should* happen when you save a persisted item. Adding to that confusion (not relevant to Person and Company which cannot be deleted) if you #save a deleted item then you end up with a new instance with same values but now no longer in a deleted state - a dup and undelete effect.

**Comment by tjchambers** [comment]
From a process concern, item #5 in my first comment above is relevant.

**Comment by tjchambers** [comment]
It would be simpler, however a regression, to eliminate #save fro Person and Company. But I stress it is a regression, since that undocumented API is accessible.

**Comment by tjchambers** [comment]
@alainmeier @backus IMHO to enforce a guideline of immutability, then #save should work either 0 times (use create!), a single time (on unpersisted non-deleted data), or generate an appropriate error response. This applies to Person, Company, and question set. 

Allowing #save on persisted data (a dup effect), or deleted data (a dup and undelete effect) rather than enforcing creation of a new Ruby Object (perhaps from the hashed attributes of a retrieved company for example) is a very unsafe technical option. It is asking for misunderstanding.

**Comment by tjchambers** [comment]
After @backus and I discussed this on HipChat the implementation change is as follows:

- #save will return false if deleted: true
- #save! will return invalidrequest if deleted: true
- #save will behave otherwise as is for Candidate which already allow edit and is documented as such in the API docs => patch

re: Person, Company and QuestionSet

- #save and #save! will function as post (like  .create)  if id.nil?
- #save will return false if id != nil 
- #save! will return invalid request if id != nil

This may mean some more special handling in the Member class. 

The client effect is that if in the past a client did the following:

```
p = Person.retrieve('...')
p.name_last = 'xyz'
p.save
```
... what happened was

- a post occurred, 
- a new person was created with a new id, 
- and the returned status was `true`. 
- The attributes from the original were in the new object, subject to what was altered.

In the proposed fix `p.save` will return `false`, no new object will be created. p will still contain the original object subject to change. 

One possible variant of that would be to deep freeze the retrieved object (Person, Company or QuestionSet) and/or to not define the setters in Collection on the new object. That would prevent those objects from responding to change since they are immutable once retrieved
